### ISSUE TITLE
fsp run 时出现错误

### ISSUE THREAD

**Issue by Skywt2003** [allanguys/font-spider-plus#19]
`fsp run` 的时候出现如下错误：

```
⠋ 配置读取完成(node:16680) UnhandledPromiseRejectionWarning: Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
    at Launcher.launch (/root/.nvm/versions/node/v12.12.0/lib/node_modules/font-spider-plus/node_modules/puppeteer/lib/Launcher.js:119:15)
    at async /root/.nvm/versions/node/v12.12.0/lib/node_modules/font-spider-plus/bin/index.js:148:33
(node:16680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16680) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

已安装 chromium……

**Comment by allanguys** [comment]
应该是chromium没有下载成功，用cnpm装应该可以解决这个问题
