### ISSUE TITLE
VUE项目， TypeError: Cannot read property 'chars' of undefined

### ISSUE THREAD

**Issue by xicode-ai** [allanguys/font-spider-plus#27]
ouis@louisdeMacBook-Pro assets % fsp run
✔ 页面分析完成

/Users/louis/.nvm/versions/node/v16.0.0/lib/node_modules/font-spider-plus/bin/index.js:250
            if(webFonts[0].chars === ''){
                           ^

TypeError: Cannot read property 'chars' of undefined
    at /Users/louis/.nvm/versions/node/v16.0.0/lib/node_modules/font-spider-plus/bin/index.js:250:28
    at CB (/Users/louis/.nvm/versions/node/v16.0.0/lib/node_modules/font-spider-plus/node_modules/fs-extra/lib/remove/rimraf.js:57:5)
    at FSReqCallback.oncomplete (node:fs:184:23)

**Comment by yutao-lin** [comment]
> ouis@louisdeMacBook-Pro assets % fsp run ✔ 页面分析完成
> 
> /Users/louis/.nvm/versions/node/v16.0.0/lib/node_modules/font-spider-plus/bin/index.js:250 if(webFonts[0].chars === ''){ ^
> 
> TypeError: Cannot read property 'chars' of undefined at /Users/louis/.nvm/versions/node/v16.0.0/lib/node_modules/font-spider-plus/bin/index.js:250:28 at CB (/Users/louis/.nvm/versions/node/v16.0.0/lib/node_modules/font-spider-plus/node_modules/fs-extra/lib/remove/rimraf.js:57:5) at FSReqCallback.oncomplete (node:fs:184:23)

你解决了吗?

**Comment by xicode-ai** [comment]
没解决
