### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by liuyuer** [allanguys/font-spider-plus#7]
Error: "//fn.qq.com/web2018../font/fn.ttf" file not found
    at Compress.min (/home/user/temp/node_modules/font-spider/src/compressor/index.js:131:29)
    at Compress.<anonymous> (/home/user/temp/node_modules/font-spider/src/compressor/index.js:63:22)
    at DestroyableTransform.emit (events.js:187:15)
    at /home/user/temp/node_modules/gulp/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (internal/process/next_tick.js:61:11)

Could you please share more examples for the parameters usage?

**Comment by allanguys** [comment]
好的 之后会补充一些。
